export const Components = [
    {
        name: "button",
        code: `// components/Button.js autogenerated using chatgpt
import React from 'react';
import PropTypes from 'prop-types';

const Button = ({ label, onClick, type = 'button', className = '', disabled = false }) => {
  return (
    <button
      type={type}
      className={\`px-4 py-2 bg-blue-500 text-white rounded \${className}\`}
      onClick={onClick}
      disabled={disabled}
    >
      {label}
    </button>
  );
};

Button.propTypes = {
  label: PropTypes.string.isRequired,
  onClick: PropTypes.func,
  type: PropTypes.oneOf(['button', 'submit', 'reset']),
  className: PropTypes.string,
  disabled: PropTypes.bool,
};

export default Button;`
    }
]